### ISSUE TITLE
Add commands to easily browse one's Google Play Music collection

### ISSUE THREAD

**Issue by Keavon** [kufii/Audioshield-PlayMusic#13]
In addition to `-al Album Name` and `-pl Playlist Name`, there are other potentially useful ways to browse your Google Play Music library and pick out songs more quickly without having to switch to the website to browse. This issue should serve as a discussion for brainstorming and deciding on which commands would be most useful. Separate issues can be created related to the implementation of any decided-on features.

After some thought, I found that the best way to design this is with a series of stackable flags. There would be three types of flags:
1. Limiter flags. These limit the results to only certain songs, such as those in your favorites or library. Possible inclusions: `-fav`, `-lib`, `-al Album Name`, `-pl Playlist Name`
2. Sort flags. These set how to sort the results. Only one sort flag is possible (any later ones should be ignored). Possible inclusions: `-plays`, `-rand`

Multiple limiter flags work on an "or" basis, so `-fav -lib` would include results from both the favorites and the library.

Useful examples include `-fav -lib Still Alive` (searching for "Still Alive" from your favorites and library rather than having to scroll through all the search results of every song on Google Play Music with that name), `-fav -rand` (displays a random selection of favorite songs), `-pl Awesome Tunes -plays` (displays results from your playlist named "Awesome Tunes" sorted with the most played songs on top).

**Comment by kufii** [comment]
Split into two new issues:

https://github.com/kufii/Audioshield-PlayMusic/issues/14

https://github.com/kufii/Audioshield-PlayMusic/issues/15
