### ISSUE TITLE
CommandNotFoundException: ConvertFrom-Json on Windows 7 (Powershell 2)

### ISSUE THREAD

**Issue by ReggX** [kufii/Audioshield-PlayMusic#22]
I get an error when launching start-game.bat

> Die Benennung "ConvertFrom-Json" wurde nicht als Name eines Cmdlet, einer Funktion, einer Skriptdatei oder eines ausführbaren Programms erkannt. Überprüfen Sie die Schreibweise des
> Namens, oder ob der Pfad korrekt ist (sofern enthalten), und wiederholen Sie den Vorgang.
> Bei D:\MyFiles\Games\audioshield\Audioshield-PlayMusic-master\start-game.ps1:39 Zeichen:58
> - $config = Get-Content -Raw config.json | ConvertFrom-Json <<<<
>   - CategoryInfo          : ObjectNotFound: (ConvertFrom-Json:String) [], CommandNotFoundException
>   - FullyQualifiedErrorId : CommandNotFoundException

Google-Fu told me that's because it's a Powershell 3 command that's not found on my Windows 7 default Powershell version 2.

**Comment by ReggX** [comment]
Fixed my problem by updating powershell via https://social.technet.microsoft.com/wiki/contents/articles/21016.how-to-install-windows-powershell-4-0.aspx

Maybe add a version check into the powershell script or at least add update instructions in the install guide.

**Comment by kufii** [comment]
Thanks for the report, didn't know it wasn't in Windows 7 by default

**Comment by kufii** [comment]
Nevermind, someone else just made one, thanks for solving the issue tho
