### ISSUE TITLE
App Won't Start

### ISSUE THREAD

**Issue by ecolbeth** [kufii/Audioshield-PlayMusic#31]
I downloaded and unzipped the folder. Ran the exe and it brings up a screen that launches a script. 

The screen keeps opening new screens and does this endlessly. 

It says:
Loading NPM Packages, over and over again. 

Thanks!

**Comment by kufii** [comment]
Sorry! This project has been broken ever since Audioshield removed SoundCloud support, see issue #30.

I unfortunately have not been able to find a feasible workaround yet.
