### ISSUE TITLE
Inital Login Fail. Google Changed Auth Methods?

### ISSUE THREAD

**Issue by harmo777** [kufii/Audioshield-PlayMusic#33]
Hi

I have downloaded the master build and extracted and ran it but have run into some issues. I have created an App Password for it in Google security settings with no success. I have tried removing 2FA from my account so i could enable "Allow less secure apps" to see if 2FA was an issue but it seems to result in the same message "Email or Password Incorrect". 

I have Google Music on my Android device as its where it is mainly used. I tried signing out of it and back it just in case that may have updated something but again no difference

I did have a look at Node.js unofficial Play Music API and noticed there had been some changes to that project very recently. Not sure if Google has changed something which has prompted the update from Jamon.

Not sure what else to check.

**Comment by Jackalopalen** [comment]
Needs to use most recent version of the play music api. that fixes the login issue, but search isn't working. The sep 18, 2016 version does work though. I went ahead and forked and fixed these two issues, this is confirmed working: https://github.com/Jackalopalen/Audioshield-PlayMusic

**Comment by kufii** [comment]
@jackalopalen hey, I kinda abandoned this project but I'm still accepting any pull requests, feel free to create one and I'll merge it over

**Comment by kufii** [comment]
Nevermind someone else just created one, thanks for finding the issue though
