### ISSUE TITLE
Displaying Google Play Music playlists in search results

### ISSUE THREAD

**Issue by Keavon** [kufii/Audioshield-PlayMusic#9]
I have no idea if this is possible or not, but it would be incredibly helpful and more useful if I could browse my Google Play Music playlists. My current process is browsing my library in Chrome via the SteamVR desktop view, picking a song, searching it in Audioshield, hoping to find it, then playing it and repeating the same tedious process. Instead, I'd love to browse through my playlists and auto-playlists (Thumbs up/Last added/Free and purchased). The way I could see this implemented would be searching a certain query such as `gpm:thumbs` or `gpm:added` or `gpm:purchased` or `gpm:playlistname` and the returned results for the search would be the ordered contents of the playlist.

**Comment by kufii** [comment]
I could probably do that, good suggestion

**Comment by Keavon** [comment]
It appears Audioshield only displays the first 50 items returned to it. That makes this challenging. Perhaps the user could type a "page number" into the search query, such as `gpm:added:2`? for page 2? Would it be possible to mod Audioshield itself to remove this limitation?

**Comment by kufii** [comment]
done, you can search for a playlist by searching `-pl <search>`

I've opened a new issue for viewing thumbs up: https://github.com/kufii/Audioshield-PlayMusic/issues/12

Last Added, and Free and Purchased will not be possible with the API I'm using

Thanks for the suggestion!

**Comment by Keavon** [comment]
> Last Added, and Free and Purchased will not be possible with the API I'm using

The closest I was able to get was `pm.getAllTracks` but that comes back alphabetical. There doesn't appear to be a sortable property like the date it was added to your library. Perhaps sorting by play count would be useful?
